import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type SeedRequest = {
  vault_path: string;
  wiki_names: string[];
  inbox_items: string[];
};

export function seedVault(req: SeedRequest): void {
  for (const wiki of req.wiki_names) {
    const wikiRoot = join(req.vault_path, "wikis", wiki);
    for (const sub of ["inbox", "concept", "synthesis", "idea", "question", "decision", "source", "guide", "journal", "task"]) {
      mkdirSync(join(wikiRoot, sub), { recursive: true });
    }
    const mapPath = join(wikiRoot, "map.md");
    if (!existsSync(mapPath)) writeFileSync(mapPath, mapStub(wiki));
    const idxPath = join(wikiRoot, "index.md");
    if (!existsSync(idxPath)) writeFileSync(idxPath, `# ${wiki} — index\n\n(generated by reindex)\n`);
  }
  if (req.wiki_names.length > 0 && req.inbox_items.length > 0) {
    const firstWiki = req.wiki_names[0];
    const today = new Date().toISOString().slice(0, 10);
    for (let i = 0; i < req.inbox_items.length; i++) {
      const slug = req.inbox_items[i].toLowerCase().split(/\s+/).slice(0, 6).join("-").replace(/[^a-z0-9-]/g, "");
      const inboxFile = join(req.vault_path, "wikis", firstWiki, "inbox", `${today}-${String(i + 1).padStart(2, "0")}-${slug || "item"}.md`);
      writeFileSync(inboxFile, `---\ncreated: ${today}\n---\n\n${req.inbox_items[i]}\n`);
    }
  }
}

function mapStub(wiki: string): string {
  return `---\nid: map\ntitle: "${wiki} — map"\ntype: map\nwiki: ${wiki}\nstatus: active\ncreated: ${new Date().toISOString().slice(0, 10)}\n---\n\n# ${wiki} — map\n\nThis wiki was seeded by \`stoa onboard\`. Edit this map as your AI files pages here.\n`;
}
