import { mkdirSync, writeFileSync, existsSync, appendFileSync, readFileSync } from "node:fs";
import { join } from "node:path";

const KEBAB = /^[a-z0-9]+(-[a-z0-9]+)*$/;
const VALID_MODES = ["idea-map", "project-doc", "learning", "mixed"] as const;
type WikiMode = typeof VALID_MODES[number];

export class WikiExistsError extends Error {
  constructor(public name: string) { super(`wiki exists: ${name}`); this.name = "WikiExistsError"; }
}

const SUBFOLDERS = [
  "inbox", "ideas", "concepts", "decisions", "specs",
  "synthesis", "guides", "journal", "tasks", "sources"
];

export interface NewWikiInput {
  name: string;
  mode: WikiMode;
  scope: string;
}

export interface NewWikiResult {
  name: string;
  path: string;
  files_created: string[];
}

export function newWiki(vaultPath: string, input: NewWikiInput): NewWikiResult {
  if (!KEBAB.test(input.name)) throw new Error(`wiki name must be kebab-case: ${input.name}`);
  if (!VALID_MODES.includes(input.mode)) throw new Error(`invalid mode: ${input.mode}`);
  const root = join(vaultPath, "wikis", input.name);
  if (existsSync(root)) throw new WikiExistsError(input.name);

  const created: string[] = [];
  mkdirSync(root, { recursive: true });
  for (const sub of SUBFOLDERS) {
    mkdirSync(join(root, sub), { recursive: true });
  }

  // CLAUDE.md
  const claudeMd = `# ${input.name} — wiki conventions\n\n**Mode:** ${input.mode}\n**Scope:** ${input.scope}\n\n## Tag vocabulary\n\n(Add wiki-specific tags here as they emerge.)\n\n## Local conventions\n\n(Add wiki-specific rules that extend the vault root CLAUDE.md.)\n`;
  writeFileSync(join(root, "CLAUDE.md"), claudeMd);
  created.push("CLAUDE.md");

  // map.md
  const today = new Date().toISOString().slice(0, 10);
  const mapMd = `---\nid: map-${input.name}\ntitle: "${input.name} map"\ntype: map\nwiki: ${input.name}\nstatus: active\ncreated: ${today}\nupdated: ${today}\nsummary: "Hand-curated entry point for the ${input.name} wiki."\n---\n\n# ${input.name}\n\n${input.scope}\n\n<!-- AUTO:start -->\n<!-- AUTO:end -->\n`;
  writeFileSync(join(root, "map.md"), mapMd);
  created.push("map.md");

  // index.md
  writeFileSync(join(root, "index.md"), `# ${input.name} — alphabetical index\n\n(Regenerated by reindex.)\n`);
  created.push("index.md");

  // log.md
  writeFileSync(join(root, "log.md"), `# ${input.name} — operations log\n\n- ${new Date().toISOString()} \`new-wiki\` by human:vault-owner: created wiki with mode=${input.mode}\n`);
  created.push("log.md");

  // REGISTRY.md update
  const regPath = join(vaultPath, "REGISTRY.md");
  const regLine = `- **${input.name}** (mode: ${input.mode}) — ${input.scope}\n`;
  if (!existsSync(regPath)) writeFileSync(regPath, "# Wikis\n\n" + regLine);
  else appendFileSync(regPath, regLine);

  return { name: input.name, path: root, files_created: created };
}
